version: '3.8'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: password
    restart: always
    networks:
      - nestjs-network
    ports:
      - "3306:3306"
    expose:
      - "3306"

networks:
  nestjs-network:
